/**
 * `openxml-ts/office-ext` umbrella entry — Epic-76.
 *
 * 聚合全部剩余扩展命名空间（109 个），使用命名空间 re-export 隔离同名类：
 *
 * ```ts
 * import { word2012Wordml, registerOfficeExtElements } from "openxml-ts/office-ext";
 * const color = new word2012Wordml.Color();
 * ```
 */

export * as ink2010Main from "./schemas-microsoft-com-ink-2010-main/generated/index.js";
export * as office200601Customui from "./schemas-microsoft-com-office-2006-01-customui/generated/index.js";
export * as office2006Activex from "./schemas-microsoft-com-office-2006-activeX/generated/index.js";
export * as office2006Coverpageprops from "./schemas-microsoft-com-office-2006-coverPageProps/generated/index.js";
export * as office2006Customdocumentinformationpanel from "./schemas-microsoft-com-office-2006-customDocumentInformationPanel/generated/index.js";
export * as office2006MetadataContenttype from "./schemas-microsoft-com-office-2006-metadata-contentType/generated/index.js";
export * as office2006MetadataCustomxsn from "./schemas-microsoft-com-office-2006-metadata-customXsn/generated/index.js";
export * as office2006MetadataLongproperties from "./schemas-microsoft-com-office-2006-metadata-longProperties/generated/index.js";
export * as office2006MetadataPropertiesMetaattributes from "./schemas-microsoft-com-office-2006-metadata-properties-metaAttributes/generated/index.js";
export * as office200907Customui from "./schemas-microsoft-com-office-2009-07-customui/generated/index.js";
export * as office2019Extlst from "./schemas-microsoft-com-office-2019-extlst/generated/index.js";
export * as office2020Miplabelmetadata from "./schemas-microsoft-com-office-2020-mipLabelMetadata/generated/index.js";
export * as officeDrawing200782Chart from "./schemas-microsoft-com-office-drawing-2007-8-2-chart/generated/index.js";
export * as officeDrawing2008Diagram from "./schemas-microsoft-com-office-drawing-2008-diagram/generated/index.js";
export * as officeDrawing2010Chartdrawing from "./schemas-microsoft-com-office-drawing-2010-chartDrawing/generated/index.js";
export * as officeDrawing2010Compatibility from "./schemas-microsoft-com-office-drawing-2010-compatibility/generated/index.js";
export * as officeDrawing2010Diagram from "./schemas-microsoft-com-office-drawing-2010-diagram/generated/index.js";
export * as officeDrawing2010Picture from "./schemas-microsoft-com-office-drawing-2010-picture/generated/index.js";
export * as officeDrawing2010Slicer from "./schemas-microsoft-com-office-drawing-2010-slicer/generated/index.js";
export * as officeDrawing2012Chart from "./schemas-microsoft-com-office-drawing-2012-chart/generated/index.js";
export * as officeDrawing2012Chartstyle from "./schemas-microsoft-com-office-drawing-2012-chartStyle/generated/index.js";
export * as officeDrawing2012Main from "./schemas-microsoft-com-office-drawing-2012-main/generated/index.js";
export * as officeDrawing2012Timeslicer from "./schemas-microsoft-com-office-drawing-2012-timeslicer/generated/index.js";
export * as officeDrawing2013MainCommand from "./schemas-microsoft-com-office-drawing-2013-main-command/generated/index.js";
export * as officeDrawing2014Chart from "./schemas-microsoft-com-office-drawing-2014-chart/generated/index.js";
export * as officeDrawing2014ChartAc from "./schemas-microsoft-com-office-drawing-2014-chart-ac/generated/index.js";
export * as officeDrawing2014Main from "./schemas-microsoft-com-office-drawing-2014-main/generated/index.js";
export * as officeDrawing201611Diagram from "./schemas-microsoft-com-office-drawing-2016-11-diagram/generated/index.js";
export * as officeDrawing201611Main from "./schemas-microsoft-com-office-drawing-2016-11-main/generated/index.js";
export * as officeDrawing201612Diagram from "./schemas-microsoft-com-office-drawing-2016-12-diagram/generated/index.js";
export * as officeDrawing2016SvgMain from "./schemas-microsoft-com-office-drawing-2016-SVG-main/generated/index.js";
export * as officeDrawing201703Chart from "./schemas-microsoft-com-office-drawing-2017-03-chart/generated/index.js";
export * as officeDrawing2017Decorative from "./schemas-microsoft-com-office-drawing-2017-decorative/generated/index.js";
export * as officeDrawing2017Model3d from "./schemas-microsoft-com-office-drawing-2017-model3d/generated/index.js";
export * as officeDrawing2018Animation from "./schemas-microsoft-com-office-drawing-2018-animation/generated/index.js";
export * as officeDrawing2018AnimationModel3d from "./schemas-microsoft-com-office-drawing-2018-animation-model3d/generated/index.js";
export * as officeDrawing2018Hyperlinkcolor from "./schemas-microsoft-com-office-drawing-2018-hyperlinkcolor/generated/index.js";
export * as officeDrawing2018Sketchyshapes from "./schemas-microsoft-com-office-drawing-2018-sketchyshapes/generated/index.js";
export * as officeDrawing2020Classificationshape from "./schemas-microsoft-com-office-drawing-2020-classificationShape/generated/index.js";
export * as officeDrawing2021Livefeed from "./schemas-microsoft-com-office-drawing-2021-livefeed/generated/index.js";
export * as officeDrawing2021Oembed from "./schemas-microsoft-com-office-drawing-2021-oembed/generated/index.js";
export * as officeDrawing2021Scriptlink from "./schemas-microsoft-com-office-drawing-2021-scriptlink/generated/index.js";
export * as officeDrawing2022Imageformula from "./schemas-microsoft-com-office-drawing-2022-imageformula/generated/index.js";
export * as officeExcel2006Main from "./schemas-microsoft-com-office-excel-2006-main/generated/index.js";
export * as officeExcel2010Spreadsheetdrawing from "./schemas-microsoft-com-office-excel-2010-spreadsheetDrawing/generated/index.js";
export * as officePowerpoint2012Main from "./schemas-microsoft-com-office-powerpoint-2012-main/generated/index.js";
export * as officePowerpoint2012Roamingsettings from "./schemas-microsoft-com-office-powerpoint-2012-roamingSettings/generated/index.js";
export * as officePowerpoint2013MainCommand from "./schemas-microsoft-com-office-powerpoint-2013-main-command/generated/index.js";
export * as officePowerpoint2015Main from "./schemas-microsoft-com-office-powerpoint-2015-main/generated/index.js";
export * as officePowerpoint201710Main from "./schemas-microsoft-com-office-powerpoint-2017-10-main/generated/index.js";
export * as officePowerpoint20173Main from "./schemas-microsoft-com-office-powerpoint-2017-3-main/generated/index.js";
export * as officePowerpoint20184Main from "./schemas-microsoft-com-office-powerpoint-2018-4-main/generated/index.js";
export * as officePowerpoint20188Main from "./schemas-microsoft-com-office-powerpoint-2018-8-main/generated/index.js";
export * as officePowerpoint201912Main from "./schemas-microsoft-com-office-powerpoint-2019-12-main/generated/index.js";
export * as officePowerpoint20199MainCommand from "./schemas-microsoft-com-office-powerpoint-2019-9-main-command/generated/index.js";
export * as officePowerpoint202002Main from "./schemas-microsoft-com-office-powerpoint-2020-02-main/generated/index.js";
export * as officePowerpoint202106Main from "./schemas-microsoft-com-office-powerpoint-2021-06-main/generated/index.js";
export * as officePowerpoint202203Main from "./schemas-microsoft-com-office-powerpoint-2022-03-main/generated/index.js";
export * as officePowerpoint202208Main from "./schemas-microsoft-com-office-powerpoint-2022-08-main/generated/index.js";
export * as officePowerpoint202302Main from "./schemas-microsoft-com-office-powerpoint-2023-02-main/generated/index.js";
export * as officeSpreadsheetml201011Ac from "./schemas-microsoft-com-office-spreadsheetml-2010-11-ac/generated/index.js";
export * as officeSpreadsheetml20111Ac from "./schemas-microsoft-com-office-spreadsheetml-2011-1-ac/generated/index.js";
export * as officeSpreadsheetml201411Main from "./schemas-microsoft-com-office-spreadsheetml-2014-11-main/generated/index.js";
export * as officeSpreadsheetml2014Revision from "./schemas-microsoft-com-office-spreadsheetml-2014-revision/generated/index.js";
export * as officeSpreadsheetml2016Pivotdefaultlayout from "./schemas-microsoft-com-office-spreadsheetml-2016-pivotdefaultlayout/generated/index.js";
export * as officeSpreadsheetml2017Dynamicarray from "./schemas-microsoft-com-office-spreadsheetml-2017-dynamicarray/generated/index.js";
export * as officeSpreadsheetml2017Richdata from "./schemas-microsoft-com-office-spreadsheetml-2017-richdata/generated/index.js";
export * as officeSpreadsheetml2017Richdata2 from "./schemas-microsoft-com-office-spreadsheetml-2017-richdata2/generated/index.js";
export * as officeSpreadsheetml2018Calcfeatures from "./schemas-microsoft-com-office-spreadsheetml-2018-calcfeatures/generated/index.js";
export * as officeSpreadsheetml2018Threadedcomments from "./schemas-microsoft-com-office-spreadsheetml-2018-threadedcomments/generated/index.js";
export * as officeSpreadsheetml2019Extlinksprops from "./schemas-microsoft-com-office-spreadsheetml-2019-extlinksprops/generated/index.js";
export * as officeSpreadsheetml2019Namedsheetviews from "./schemas-microsoft-com-office-spreadsheetml-2019-namedsheetviews/generated/index.js";
export * as officeSpreadsheetml2020Pivotnov2020 from "./schemas-microsoft-com-office-spreadsheetml-2020-pivotNov2020/generated/index.js";
export * as officeSpreadsheetml2020Richdatawebimage from "./schemas-microsoft-com-office-spreadsheetml-2020-richdatawebimage/generated/index.js";
export * as officeSpreadsheetml2020Richvaluerefresh from "./schemas-microsoft-com-office-spreadsheetml-2020-richvaluerefresh/generated/index.js";
export * as officeSpreadsheetml2020Threadedcomments2 from "./schemas-microsoft-com-office-spreadsheetml-2020-threadedcomments2/generated/index.js";
export * as officeSpreadsheetml2021Extlinks2021 from "./schemas-microsoft-com-office-spreadsheetml-2021-extlinks2021/generated/index.js";
export * as officeSpreadsheetml2022Featurepropertybag from "./schemas-microsoft-com-office-spreadsheetml-2022-featurepropertybag/generated/index.js";
export * as officeSpreadsheetml2022Pivotrichdata from "./schemas-microsoft-com-office-spreadsheetml-2022-pivotRichData/generated/index.js";
export * as officeSpreadsheetml2022Pivotversioninfo from "./schemas-microsoft-com-office-spreadsheetml-2022-pivotVersionInfo/generated/index.js";
export * as officeSpreadsheetml2022Richvaluerel from "./schemas-microsoft-com-office-spreadsheetml-2022-richvaluerel/generated/index.js";
export * as officeSpreadsheetml2023Datasourceversioning from "./schemas-microsoft-com-office-spreadsheetml-2023-dataSourceVersioning/generated/index.js";
export * as officeSpreadsheetml2023Externalcodeservice from "./schemas-microsoft-com-office-spreadsheetml-2023-externalCodeService/generated/index.js";
export * as officeSpreadsheetml2023Msforms from "./schemas-microsoft-com-office-spreadsheetml-2023-msForms/generated/index.js";
export * as officeSpreadsheetml2023Pivot2023calculation from "./schemas-microsoft-com-office-spreadsheetml-2023-pivot2023Calculation/generated/index.js";
export * as officeSpreadsheetml2024Pivotautorefresh from "./schemas-microsoft-com-office-spreadsheetml-2024-pivotAutoRefresh/generated/index.js";
export * as officeSpreadsheetml2024Pivotdynamicarrays from "./schemas-microsoft-com-office-spreadsheetml-2024-pivotDynamicArrays/generated/index.js";
export * as officeSpreadsheetml2024Workbookcompatibilityversion from "./schemas-microsoft-com-office-spreadsheetml-2024-workbookCompatibilityVersion/generated/index.js";
export * as officeSpreadsheetml2025Externalcodeservice2 from "./schemas-microsoft-com-office-spreadsheetml-2025-externalCodeService2/generated/index.js";
export * as officeSpreadsheetml2025Pivotdatasource from "./schemas-microsoft-com-office-spreadsheetml-2025-pivotDataSource/generated/index.js";
export * as officeTasks2019Documenttasks from "./schemas-microsoft-com-office-tasks-2019-documenttasks/generated/index.js";
export * as officeThememl2012Main from "./schemas-microsoft-com-office-thememl-2012-main/generated/index.js";
export * as officeWebextensionsTaskpanes201011 from "./schemas-microsoft-com-office-webextensions-taskpanes-2010-11/generated/index.js";
export * as officeWebextensionsWebextension201011 from "./schemas-microsoft-com-office-webextensions-webextension-2010-11/generated/index.js";
export * as officeWord2006Wordml from "./schemas-microsoft-com-office-word-2006-wordml/generated/index.js";
export * as officeWord2010Wordprocessingcanvas from "./schemas-microsoft-com-office-word-2010-wordprocessingCanvas/generated/index.js";
export * as officeWord2010Wordprocessingdrawing from "./schemas-microsoft-com-office-word-2010-wordprocessingDrawing/generated/index.js";
export * as officeWord2010Wordprocessinggroup from "./schemas-microsoft-com-office-word-2010-wordprocessingGroup/generated/index.js";
export * as officeWord2010Wordprocessingshape from "./schemas-microsoft-com-office-word-2010-wordprocessingShape/generated/index.js";
export * as officeWord2012Wordml from "./schemas-microsoft-com-office-word-2012-wordml/generated/index.js";
export * as officeWord2012Wordprocessingdrawing from "./schemas-microsoft-com-office-word-2012-wordprocessingDrawing/generated/index.js";
export * as officeWord2015WordmlSymex from "./schemas-microsoft-com-office-word-2015-wordml-symex/generated/index.js";
export * as officeWord2016WordmlCid from "./schemas-microsoft-com-office-word-2016-wordml-cid/generated/index.js";
export * as officeWord2018Wordml from "./schemas-microsoft-com-office-word-2018-wordml/generated/index.js";
export * as officeWord2018WordmlCex from "./schemas-microsoft-com-office-word-2018-wordml-cex/generated/index.js";
export * as officeWord2020Oembed from "./schemas-microsoft-com-office-word-2020-oembed/generated/index.js";
export * as officeDocument2006Characteristics from "./schemas-openxmlformats-org-officeDocument-2006-characteristics/generated/index.js";
export * as ns200304Emma from "./www-w3-org-2003-04-emma/generated/index.js";
export * as ns2003Inkml from "./www-w3-org-2003-InkML/generated/index.js";

// ─── registry imports ─────────────────────────────────────────────────────────
import { registerInk2010MainElements } from "./schemas-microsoft-com-ink-2010-main/generated/_registry.js";
import { register200601CustomuiElements } from "./schemas-microsoft-com-office-2006-01-customui/generated/_registry.js";
import { register2006ActiveXElements } from "./schemas-microsoft-com-office-2006-activeX/generated/_registry.js";
import { register2006CoverPagePropsElements } from "./schemas-microsoft-com-office-2006-coverPageProps/generated/_registry.js";
import { register2006CustomDocumentInformationPanelElements } from "./schemas-microsoft-com-office-2006-customDocumentInformationPanel/generated/_registry.js";
import { register2006MetadataContentTypeElements } from "./schemas-microsoft-com-office-2006-metadata-contentType/generated/_registry.js";
import { register2006MetadataCustomXsnElements } from "./schemas-microsoft-com-office-2006-metadata-customXsn/generated/_registry.js";
import { register2006MetadataLongPropertiesElements } from "./schemas-microsoft-com-office-2006-metadata-longProperties/generated/_registry.js";
import { registerMetadataPropertiesMetaAttributesElements } from "./schemas-microsoft-com-office-2006-metadata-properties-metaAttributes/generated/_registry.js";
import { register200907CustomuiElements } from "./schemas-microsoft-com-office-2009-07-customui/generated/_registry.js";
import { register2019ExtlstElements } from "./schemas-microsoft-com-office-2019-extlst/generated/_registry.js";
import { register2020MipLabelMetadataElements } from "./schemas-microsoft-com-office-2020-mipLabelMetadata/generated/_registry.js";
import { register82ChartElements } from "./schemas-microsoft-com-office-drawing-2007-8-2-chart/generated/_registry.js";
import { registerDrawing2008DiagramElements } from "./schemas-microsoft-com-office-drawing-2008-diagram/generated/_registry.js";
import { registerDrawing2010ChartDrawingElements } from "./schemas-microsoft-com-office-drawing-2010-chartDrawing/generated/_registry.js";
import { registerDrawing2010CompatibilityElements } from "./schemas-microsoft-com-office-drawing-2010-compatibility/generated/_registry.js";
import { registerDrawing2010DiagramElements } from "./schemas-microsoft-com-office-drawing-2010-diagram/generated/_registry.js";
import { registerDrawing2010PictureElements } from "./schemas-microsoft-com-office-drawing-2010-picture/generated/_registry.js";
import { registerDrawing2010SlicerElements } from "./schemas-microsoft-com-office-drawing-2010-slicer/generated/_registry.js";
import { registerDrawing2012ChartElements } from "./schemas-microsoft-com-office-drawing-2012-chart/generated/_registry.js";
import { registerDrawing2012ChartStyleElements } from "./schemas-microsoft-com-office-drawing-2012-chartStyle/generated/_registry.js";
import { registerDrawing2012MainElements } from "./schemas-microsoft-com-office-drawing-2012-main/generated/_registry.js";
import { registerDrawing2012TimeslicerElements } from "./schemas-microsoft-com-office-drawing-2012-timeslicer/generated/_registry.js";
import { registerDrawing2013CommandElements } from "./schemas-microsoft-com-office-drawing-2013-main-command/generated/_registry.js";
import { register2014ChartAcElements } from "./schemas-microsoft-com-office-drawing-2014-chart-ac/generated/_registry.js";
import { registerDrawing2014ChartElements } from "./schemas-microsoft-com-office-drawing-2014-chart/generated/_registry.js";
import { registerDrawing2014MainElements } from "./schemas-microsoft-com-office-drawing-2014-main/generated/_registry.js";
import { register201611DiagramElements } from "./schemas-microsoft-com-office-drawing-2016-11-diagram/generated/_registry.js";
import { register201611MainElements } from "./schemas-microsoft-com-office-drawing-2016-11-main/generated/_registry.js";
import { register201612DiagramElements } from "./schemas-microsoft-com-office-drawing-2016-12-diagram/generated/_registry.js";
import { register2016SVGMainElements } from "./schemas-microsoft-com-office-drawing-2016-SVG-main/generated/_registry.js";
import { register201703ChartElements } from "./schemas-microsoft-com-office-drawing-2017-03-chart/generated/_registry.js";
import { registerDrawing2017DecorativeElements } from "./schemas-microsoft-com-office-drawing-2017-decorative/generated/_registry.js";
import { registerDrawing2017Model3dElements } from "./schemas-microsoft-com-office-drawing-2017-model3d/generated/_registry.js";
import { register2018AnimationModel3dElements } from "./schemas-microsoft-com-office-drawing-2018-animation-model3d/generated/_registry.js";
import { registerDrawing2018AnimationElements } from "./schemas-microsoft-com-office-drawing-2018-animation/generated/_registry.js";
import { registerDrawing2018HyperlinkcolorElements } from "./schemas-microsoft-com-office-drawing-2018-hyperlinkcolor/generated/_registry.js";
import { registerDrawing2018SketchyshapesElements } from "./schemas-microsoft-com-office-drawing-2018-sketchyshapes/generated/_registry.js";
import { registerDrawing2020ClassificationShapeElements } from "./schemas-microsoft-com-office-drawing-2020-classificationShape/generated/_registry.js";
import { registerDrawing2021LivefeedElements } from "./schemas-microsoft-com-office-drawing-2021-livefeed/generated/_registry.js";
import { registerDrawing2021OembedElements } from "./schemas-microsoft-com-office-drawing-2021-oembed/generated/_registry.js";
import { registerDrawing2021ScriptlinkElements } from "./schemas-microsoft-com-office-drawing-2021-scriptlink/generated/_registry.js";
import { registerDrawing2022ImageformulaElements } from "./schemas-microsoft-com-office-drawing-2022-imageformula/generated/_registry.js";
import { registerExcel2006MainElements } from "./schemas-microsoft-com-office-excel-2006-main/generated/_registry.js";
import { registerExcel2010SpreadsheetDrawingElements } from "./schemas-microsoft-com-office-excel-2010-spreadsheetDrawing/generated/_registry.js";
import { registerPowerpoint2012MainElements } from "./schemas-microsoft-com-office-powerpoint-2012-main/generated/_registry.js";
import { registerPowerpoint2012RoamingSettingsElements } from "./schemas-microsoft-com-office-powerpoint-2012-roamingSettings/generated/_registry.js";
import { registerPpt2013CommandElements } from "./schemas-microsoft-com-office-powerpoint-2013-main-command/generated/_registry.js";
import { registerPowerpoint2015MainElements } from "./schemas-microsoft-com-office-powerpoint-2015-main/generated/_registry.js";
import { register20173MainElements } from "./schemas-microsoft-com-office-powerpoint-2017-3-main/generated/_registry.js";
import { register201710MainElements } from "./schemas-microsoft-com-office-powerpoint-2017-10-main/generated/_registry.js";
import { register20184MainElements } from "./schemas-microsoft-com-office-powerpoint-2018-4-main/generated/_registry.js";
import { register20188MainElements } from "./schemas-microsoft-com-office-powerpoint-2018-8-main/generated/_registry.js";
import { register9MainCommandElements } from "./schemas-microsoft-com-office-powerpoint-2019-9-main-command/generated/_registry.js";
import { register201912MainElements } from "./schemas-microsoft-com-office-powerpoint-2019-12-main/generated/_registry.js";
import { register202002MainElements } from "./schemas-microsoft-com-office-powerpoint-2020-02-main/generated/_registry.js";
import { register202106MainElements } from "./schemas-microsoft-com-office-powerpoint-2021-06-main/generated/_registry.js";
import { register202203MainElements } from "./schemas-microsoft-com-office-powerpoint-2022-03-main/generated/_registry.js";
import { register202208MainElements } from "./schemas-microsoft-com-office-powerpoint-2022-08-main/generated/_registry.js";
import { register202302MainElements } from "./schemas-microsoft-com-office-powerpoint-2023-02-main/generated/_registry.js";
import { register201011AcElements } from "./schemas-microsoft-com-office-spreadsheetml-2010-11-ac/generated/_registry.js";
import { register20111AcElements } from "./schemas-microsoft-com-office-spreadsheetml-2011-1-ac/generated/_registry.js";
import { register201411MainElements } from "./schemas-microsoft-com-office-spreadsheetml-2014-11-main/generated/_registry.js";
import { registerSpreadsheetml2014RevisionElements } from "./schemas-microsoft-com-office-spreadsheetml-2014-revision/generated/_registry.js";
import { registerSpreadsheetml2016PivotdefaultlayoutElements } from "./schemas-microsoft-com-office-spreadsheetml-2016-pivotdefaultlayout/generated/_registry.js";
import { registerSpreadsheetml2017DynamicarrayElements } from "./schemas-microsoft-com-office-spreadsheetml-2017-dynamicarray/generated/_registry.js";
import { registerSpreadsheetml2017RichdataElements } from "./schemas-microsoft-com-office-spreadsheetml-2017-richdata/generated/_registry.js";
import { registerSpreadsheetml2017Richdata2Elements } from "./schemas-microsoft-com-office-spreadsheetml-2017-richdata2/generated/_registry.js";
import { registerSpreadsheetml2018CalcfeaturesElements } from "./schemas-microsoft-com-office-spreadsheetml-2018-calcfeatures/generated/_registry.js";
import { registerSpreadsheetml2018ThreadedcommentsElements } from "./schemas-microsoft-com-office-spreadsheetml-2018-threadedcomments/generated/_registry.js";
import { registerSpreadsheetml2019ExtlinkspropsElements } from "./schemas-microsoft-com-office-spreadsheetml-2019-extlinksprops/generated/_registry.js";
import { registerSpreadsheetml2019NamedsheetviewsElements } from "./schemas-microsoft-com-office-spreadsheetml-2019-namedsheetviews/generated/_registry.js";
import { registerSpreadsheetml2020PivotNov2020Elements } from "./schemas-microsoft-com-office-spreadsheetml-2020-pivotNov2020/generated/_registry.js";
import { registerSpreadsheetml2020RichdatawebimageElements } from "./schemas-microsoft-com-office-spreadsheetml-2020-richdatawebimage/generated/_registry.js";
import { registerSpreadsheetml2020RichvaluerefreshElements } from "./schemas-microsoft-com-office-spreadsheetml-2020-richvaluerefresh/generated/_registry.js";
import { registerSpreadsheetml2020Threadedcomments2Elements } from "./schemas-microsoft-com-office-spreadsheetml-2020-threadedcomments2/generated/_registry.js";
import { registerSpreadsheetml2021Extlinks2021Elements } from "./schemas-microsoft-com-office-spreadsheetml-2021-extlinks2021/generated/_registry.js";
import { registerSpreadsheetml2022FeaturepropertybagElements } from "./schemas-microsoft-com-office-spreadsheetml-2022-featurepropertybag/generated/_registry.js";
import { registerSpreadsheetml2022PivotRichDataElements } from "./schemas-microsoft-com-office-spreadsheetml-2022-pivotRichData/generated/_registry.js";
import { registerSpreadsheetml2022PivotVersionInfoElements } from "./schemas-microsoft-com-office-spreadsheetml-2022-pivotVersionInfo/generated/_registry.js";
import { registerSpreadsheetml2022RichvaluerelElements } from "./schemas-microsoft-com-office-spreadsheetml-2022-richvaluerel/generated/_registry.js";
import { registerSpreadsheetml2023DataSourceVersioningElements } from "./schemas-microsoft-com-office-spreadsheetml-2023-dataSourceVersioning/generated/_registry.js";
import { registerSpreadsheetml2023ExternalCodeServiceElements } from "./schemas-microsoft-com-office-spreadsheetml-2023-externalCodeService/generated/_registry.js";
import { registerSpreadsheetml2023MsFormsElements } from "./schemas-microsoft-com-office-spreadsheetml-2023-msForms/generated/_registry.js";
import { registerSpreadsheetml2023Pivot2023CalculationElements } from "./schemas-microsoft-com-office-spreadsheetml-2023-pivot2023Calculation/generated/_registry.js";
import { registerSpreadsheetml2024PivotAutoRefreshElements } from "./schemas-microsoft-com-office-spreadsheetml-2024-pivotAutoRefresh/generated/_registry.js";
import { registerSpreadsheetml2024PivotDynamicArraysElements } from "./schemas-microsoft-com-office-spreadsheetml-2024-pivotDynamicArrays/generated/_registry.js";
import { registerSpreadsheetml2024WorkbookCompatibilityVersionElements } from "./schemas-microsoft-com-office-spreadsheetml-2024-workbookCompatibilityVersion/generated/_registry.js";
import { registerSpreadsheetml2025ExternalCodeService2Elements } from "./schemas-microsoft-com-office-spreadsheetml-2025-externalCodeService2/generated/_registry.js";
import { registerSpreadsheetml2025PivotDataSourceElements } from "./schemas-microsoft-com-office-spreadsheetml-2025-pivotDataSource/generated/_registry.js";
import { registerTasks2019DocumenttasksElements } from "./schemas-microsoft-com-office-tasks-2019-documenttasks/generated/_registry.js";
import { registerThememl2012MainElements } from "./schemas-microsoft-com-office-thememl-2012-main/generated/_registry.js";
import { registerTaskpanes201011Elements } from "./schemas-microsoft-com-office-webextensions-taskpanes-2010-11/generated/_registry.js";
import { registerWebextension201011Elements } from "./schemas-microsoft-com-office-webextensions-webextension-2010-11/generated/_registry.js";
import { registerWord2006WordmlElements } from "./schemas-microsoft-com-office-word-2006-wordml/generated/_registry.js";
import { registerWord2010WordprocessingCanvasElements } from "./schemas-microsoft-com-office-word-2010-wordprocessingCanvas/generated/_registry.js";
import { registerWord2010WordprocessingDrawingElements } from "./schemas-microsoft-com-office-word-2010-wordprocessingDrawing/generated/_registry.js";
import { registerWord2010WordprocessingGroupElements } from "./schemas-microsoft-com-office-word-2010-wordprocessingGroup/generated/_registry.js";
import { registerWord2010WordprocessingShapeElements } from "./schemas-microsoft-com-office-word-2010-wordprocessingShape/generated/_registry.js";
import { registerWord2012WordmlElements } from "./schemas-microsoft-com-office-word-2012-wordml/generated/_registry.js";
import { registerWord2012WordprocessingDrawingElements } from "./schemas-microsoft-com-office-word-2012-wordprocessingDrawing/generated/_registry.js";
import { register2015WordmlSymexElements } from "./schemas-microsoft-com-office-word-2015-wordml-symex/generated/_registry.js";
import { register2016WordmlCidElements } from "./schemas-microsoft-com-office-word-2016-wordml-cid/generated/_registry.js";
import { register2018WordmlCexElements } from "./schemas-microsoft-com-office-word-2018-wordml-cex/generated/_registry.js";
import { registerWord2018WordmlElements } from "./schemas-microsoft-com-office-word-2018-wordml/generated/_registry.js";
import { registerWord2020OembedElements } from "./schemas-microsoft-com-office-word-2020-oembed/generated/_registry.js";
import { registerOfficeDocument2006CharacteristicsElements } from "./schemas-openxmlformats-org-officeDocument-2006-characteristics/generated/_registry.js";
import { register200304EmmaElements } from "./www-w3-org-2003-04-emma/generated/_registry.js";
import { register2003InkMLElements } from "./www-w3-org-2003-InkML/generated/_registry.js";

import type { ElementRegistry } from "../element/index.js";

/**
 * 把全部 109 个 office-ext 扩展命名空间的具体 element 类注册到给定 ElementRegistry。
 *
 * 调用方按需 import 此函数以启用 typed XML 反序列化（ADR-012）。
 */
export function registerOfficeExtElements(registry: ElementRegistry): void {
  registerInk2010MainElements(registry);
  register200601CustomuiElements(registry);
  register2006ActiveXElements(registry);
  register2006CoverPagePropsElements(registry);
  register2006CustomDocumentInformationPanelElements(registry);
  register2006MetadataContentTypeElements(registry);
  register2006MetadataCustomXsnElements(registry);
  register2006MetadataLongPropertiesElements(registry);
  registerMetadataPropertiesMetaAttributesElements(registry);
  register200907CustomuiElements(registry);
  register2019ExtlstElements(registry);
  register2020MipLabelMetadataElements(registry);
  register82ChartElements(registry);
  registerDrawing2008DiagramElements(registry);
  registerDrawing2010ChartDrawingElements(registry);
  registerDrawing2010CompatibilityElements(registry);
  registerDrawing2010DiagramElements(registry);
  registerDrawing2010PictureElements(registry);
  registerDrawing2010SlicerElements(registry);
  registerDrawing2012ChartElements(registry);
  registerDrawing2012ChartStyleElements(registry);
  registerDrawing2012MainElements(registry);
  registerDrawing2012TimeslicerElements(registry);
  registerDrawing2013CommandElements(registry);
  registerDrawing2014ChartElements(registry);
  register2014ChartAcElements(registry);
  registerDrawing2014MainElements(registry);
  register201611DiagramElements(registry);
  register201611MainElements(registry);
  register201612DiagramElements(registry);
  register2016SVGMainElements(registry);
  register201703ChartElements(registry);
  registerDrawing2017DecorativeElements(registry);
  registerDrawing2017Model3dElements(registry);
  registerDrawing2018AnimationElements(registry);
  register2018AnimationModel3dElements(registry);
  registerDrawing2018HyperlinkcolorElements(registry);
  registerDrawing2018SketchyshapesElements(registry);
  registerDrawing2020ClassificationShapeElements(registry);
  registerDrawing2021LivefeedElements(registry);
  registerDrawing2021OembedElements(registry);
  registerDrawing2021ScriptlinkElements(registry);
  registerDrawing2022ImageformulaElements(registry);
  registerExcel2006MainElements(registry);
  registerExcel2010SpreadsheetDrawingElements(registry);
  registerPowerpoint2012MainElements(registry);
  registerPowerpoint2012RoamingSettingsElements(registry);
  registerPpt2013CommandElements(registry);
  registerPowerpoint2015MainElements(registry);
  register201710MainElements(registry);
  register20173MainElements(registry);
  register20184MainElements(registry);
  register20188MainElements(registry);
  register201912MainElements(registry);
  register9MainCommandElements(registry);
  register202002MainElements(registry);
  register202106MainElements(registry);
  register202203MainElements(registry);
  register202208MainElements(registry);
  register202302MainElements(registry);
  register201011AcElements(registry);
  register20111AcElements(registry);
  register201411MainElements(registry);
  registerSpreadsheetml2014RevisionElements(registry);
  registerSpreadsheetml2016PivotdefaultlayoutElements(registry);
  registerSpreadsheetml2017DynamicarrayElements(registry);
  registerSpreadsheetml2017RichdataElements(registry);
  registerSpreadsheetml2017Richdata2Elements(registry);
  registerSpreadsheetml2018CalcfeaturesElements(registry);
  registerSpreadsheetml2018ThreadedcommentsElements(registry);
  registerSpreadsheetml2019ExtlinkspropsElements(registry);
  registerSpreadsheetml2019NamedsheetviewsElements(registry);
  registerSpreadsheetml2020PivotNov2020Elements(registry);
  registerSpreadsheetml2020RichdatawebimageElements(registry);
  registerSpreadsheetml2020RichvaluerefreshElements(registry);
  registerSpreadsheetml2020Threadedcomments2Elements(registry);
  registerSpreadsheetml2021Extlinks2021Elements(registry);
  registerSpreadsheetml2022FeaturepropertybagElements(registry);
  registerSpreadsheetml2022PivotRichDataElements(registry);
  registerSpreadsheetml2022PivotVersionInfoElements(registry);
  registerSpreadsheetml2022RichvaluerelElements(registry);
  registerSpreadsheetml2023DataSourceVersioningElements(registry);
  registerSpreadsheetml2023ExternalCodeServiceElements(registry);
  registerSpreadsheetml2023MsFormsElements(registry);
  registerSpreadsheetml2023Pivot2023CalculationElements(registry);
  registerSpreadsheetml2024PivotAutoRefreshElements(registry);
  registerSpreadsheetml2024PivotDynamicArraysElements(registry);
  registerSpreadsheetml2024WorkbookCompatibilityVersionElements(registry);
  registerSpreadsheetml2025ExternalCodeService2Elements(registry);
  registerSpreadsheetml2025PivotDataSourceElements(registry);
  registerTasks2019DocumenttasksElements(registry);
  registerThememl2012MainElements(registry);
  registerTaskpanes201011Elements(registry);
  registerWebextension201011Elements(registry);
  registerWord2006WordmlElements(registry);
  registerWord2010WordprocessingCanvasElements(registry);
  registerWord2010WordprocessingDrawingElements(registry);
  registerWord2010WordprocessingGroupElements(registry);
  registerWord2010WordprocessingShapeElements(registry);
  registerWord2012WordmlElements(registry);
  registerWord2012WordprocessingDrawingElements(registry);
  register2015WordmlSymexElements(registry);
  register2016WordmlCidElements(registry);
  registerWord2018WordmlElements(registry);
  register2018WordmlCexElements(registry);
  registerWord2020OembedElements(registry);
  registerOfficeDocument2006CharacteristicsElements(registry);
  register200304EmmaElements(registry);
  register2003InkMLElements(registry);
}
