/**
 * Shared types for the Epic-78 OpenXmlValidator constraint system.
 *
 * These types are used both by the generated constraint files
 * (src/validation/constraints/*.ts) and the validator engine.
 */

import type { FileFormatVersions } from "../markup-compat/file-format-versions.js";

// ---- Normalized particle node types ----

/** A leaf entry: one allowed child element with cardinality. */
export interface ParticleLeaf {
  readonly kind: "leaf";
  /** Namespace URI of the allowed child element. */
  readonly ns: string;
  /** Local name of the allowed child element. */
  readonly local: string;
  /** Minimum occurrences (0 = optional, 1 = required). */
  readonly min: number;
  /** Maximum occurrences; "unbounded" means no limit. */
  readonly max: number | "unbounded";
  /** Minimum Office version required for this leaf to be valid (e.g. "Office2010"). */
  readonly initialVersion?: string;
  /** If set, only children whose constructor.name matches this class are accepted.
   *  Used to distinguish elements that share the same tag (e.g. LeftMargin vs TableCellLeftMargin). */
  readonly expectedClassName?: string;
}

/** A composite particle (Sequence / Choice / All / Group). */
export interface ParticleComposite {
  readonly kind: "sequence" | "choice" | "all" | "group";
  readonly min: number;
  readonly max: number | "unbounded";
  readonly items: readonly ParticleNode[];
  /** Minimum Office version required for this composite to be valid (e.g. "Office2010"). */
  readonly initialVersion?: string;
}

/** A wildcard particle (xsd:any). Matches any element in the specified namespace. */
export interface ParticleAny {
  readonly kind: "any";
  readonly min: number;
  readonly max: number | "unbounded";
}

export type ParticleNode = ParticleLeaf | ParticleComposite | ParticleAny;

/** Top-level particle constraint for an element. */
export interface NormalizedParticle {
  readonly root: ParticleNode;
}

/** Per-attribute value constraint (string length / number range / type validation). */
export interface AttrConstraint {
  /** The attribute qname as used in the element (e.g. "w:author", or "name"). */
  readonly qname: string;
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly minValue?: number;
  readonly maxValue?: number;
  /**
   * Type hint for validating the attribute value's content type.
   * - "hexBinary": validate hex string format and optional byte length
   * - "base64Binary": validate base64 string format
   * - "enum": validate value is in enumMembers list
   * - "list": validate whitespace-separated list items
   * - "uint32": validate value can be parsed as UInt32
   */
  readonly typeHint?: "hexBinary" | "base64Binary" | "enum" | "list" | "uint32" | "onOff";
  /** Valid enum member values (used when typeHint is "enum"). */
  readonly enumMembers?: readonly string[];
  /** Exact byte length for hexBinary validation. */
  readonly length?: number;
}

/**
 * A version-tagged required attribute entry.
 *
 * When `minVersion` is set, the attribute is only required for targets at or above that version.
 * When `maxVersion` is set, the attribute is required only for targets at or below that version.
 * When neither is set, the attribute is unconditionally required (same as a plain string in requiredAttrs).
 * When `optional` is true, this entry declares that the attribute is NOT required at this version
 * (used to override an earlier required declaration).
 */
export interface VersionedRequiredAttr {
  /** The attribute qname (e.g. "w:val"). */
  readonly qname: string;
  /**
   * Minimum FileFormatVersions value at which this required constraint applies.
   * The attribute is required when target >= minVersion.
   * Absent means "no lower bound" (applies to all older versions too).
   */
  readonly minVersion?: FileFormatVersions;
  /**
   * Maximum FileFormatVersions value at which this required constraint applies.
   * The attribute is required when target <= maxVersion.
   * Absent means "no upper bound".
   */
  readonly maxVersion?: FileFormatVersions;
  /**
   * If true, this entry declares the attribute as NOT required at this version range.
   * Used for IsRequired=False overrides.
   */
  readonly optional?: true;
}

/**
 * Constraint data for a single element class.
 * Generated by tools/schema-codegen/gen-constraints.ts.
 */
export interface ElementConstraint {
  /** .NET class name, used as lookup key. */
  readonly className: string;
  /** Namespace URI of the element. */
  readonly namespaceUri: string;
  /** XML local name of the element. */
  readonly localName: string;
  /** Normalized particle (allowed children + cardinality + ordering). */
  readonly particle?: NormalizedParticle;
  /**
   * Required attribute qnames (unconditionally required, from RequiredValidator with no version).
   * For version-conditional required attrs, see versionedRequiredAttrs.
   */
  readonly requiredAttrs?: readonly string[];
  /**
   * Version-conditional required attributes (from RequiredValidator with Version field).
   * Each entry specifies which versions the required constraint applies to.
   */
  readonly versionedRequiredAttrs?: readonly VersionedRequiredAttr[];
  /**
   * Complete list of known legal attribute qnames for this element.
   * When present, enables Sch_UndeclaredAttribute checking: any extended attribute
   * not in this list (or in requiredAttrs/attrConstraints/versionedKnownAttrs)
   * is reported as undeclared.
   */
  readonly knownAttrs?: readonly string[];
  /**
   * Version-conditional known attribute qnames.
   * Attributes only declared for this element starting from a specific Office version.
   * When the target version does not meet initialVersion, the attribute is treated as undeclared.
   */
  readonly versionedKnownAttrs?: readonly {
    readonly qname: string;
    readonly initialVersion: string;
  }[];
  /** Per-attribute value constraints (string length / number range). */
  readonly attrConstraints?: readonly AttrConstraint[];
}
