/**
 * Shared types for the Epic-78 OpenXmlValidator constraint system.
 *
 * These types are used both by the generated constraint files
 * (src/validation/constraints/*.ts) and the validator engine.
 */

// ---- Normalized particle node types ----

/** A leaf entry: one allowed child element with cardinality. */
export interface ParticleLeaf {
  readonly kind: "leaf";
  /** Namespace URI of the allowed child element. */
  readonly ns: string;
  /** Local name of the allowed child element. */
  readonly local: string;
  /** Minimum occurrences (0 = optional, 1 = required). */
  readonly min: number;
  /** Maximum occurrences; "unbounded" means no limit. */
  readonly max: number | "unbounded";
}

/** A composite particle (Sequence / Choice / All / Group). */
export interface ParticleComposite {
  readonly kind: "sequence" | "choice" | "all" | "group";
  readonly min: number;
  readonly max: number | "unbounded";
  readonly items: readonly ParticleNode[];
}

export type ParticleNode = ParticleLeaf | ParticleComposite;

/** Top-level particle constraint for an element. */
export interface NormalizedParticle {
  readonly root: ParticleNode;
}

/** Per-attribute value constraint (string length / number range). */
export interface AttrConstraint {
  /** The attribute qname as used in the element (e.g. "w:author", or "name"). */
  readonly qname: string;
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly minValue?: number;
  readonly maxValue?: number;
}

/**
 * Constraint data for a single element class.
 * Generated by tools/schema-codegen/gen-constraints.ts.
 */
export interface ElementConstraint {
  /** .NET class name, used as lookup key. */
  readonly className: string;
  /** Namespace URI of the element. */
  readonly namespaceUri: string;
  /** XML local name of the element. */
  readonly localName: string;
  /** Normalized particle (allowed children + cardinality + ordering). */
  readonly particle?: NormalizedParticle;
  /** Required attribute qnames (from RequiredValidator). */
  readonly requiredAttrs?: readonly string[];
  /** Per-attribute value constraints (string length / number range). */
  readonly attrConstraints?: readonly AttrConstraint[];
}
