// THIS FILE IS GENERATED BY tools/schema-codegen/gen-constraints.ts. DO NOT EDIT.
// Source: ../../github/Open-XML-SDK/data/schemas/schemas_microsoft_com_office_spreadsheetml_2009_9_main.json
import type { ElementConstraint } from "../types.js";

export const constraints: ReadonlyArray<ElementConstraint> = [
  {
    className: "ArgumentDescription",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "argumentDescription",
    requiredAttrs: [":index"],
  },
  {
    className: "ArgumentDescriptions",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "argumentDescriptions",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "argumentDescription", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "CacheHierarchy",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "cacheHierarchy",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "setLevels", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "CalculatedMember",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "calculatedMember",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "tupleSet", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "CalculatedMembers",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "calculatedMembers",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "calculatedMember", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "ColorScale",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "colorScale",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "cfvo", min: 2, max: "unbounded" },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "color", min: 2, max: "unbounded" }
      ] }
    },
  },
  {
    className: "ConditionalFormat",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "conditionalFormat",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotAreas", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":id"],
  },
  {
    className: "ConditionalFormats",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "conditionalFormats",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "conditionalFormat", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "ConditionalFormatting",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "conditionalFormatting",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "cfRule", min: 0, max: "unbounded" },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sqref", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ConditionalFormattingIcon",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "cfIcon",
    requiredAttrs: [":iconSet", ":iconId"],
  },
  {
    className: "ConditionalFormattingRule",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "cfRule",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 0, max: 3 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorScale", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "dataBar", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "iconSet", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "dxf", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ConditionalFormattings",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "conditionalFormattings",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "conditionalFormatting", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "ConditionalFormattingValueObject",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "cfvo",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":type"],
  },
  {
    className: "Connection",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "connection",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "calculatedMembers", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "CustomFilters",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "customFilters",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "customFilter", min: 1, max: 2 }
      ] }
    },
  },
  {
    className: "DataBar",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "dataBar",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "cfvo", min: 2, max: 2 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "fillColor", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "borderColor", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "negativeFillColor", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "negativeBorderColor", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "axisColor", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "DatastoreItem",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "datastoreItem",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":id"],
  },
  {
    className: "DataValidation",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "dataValidation",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "formula1", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "formula2", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sqref", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "DataValidationForumla1",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "formula1",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "DataValidationForumla2",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "formula2",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "DataValidations",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "dataValidations",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "dataValidation", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "DdeValues",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "values",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "value", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "DefinedName",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "definedName",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "argumentDescriptions", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":name"],
  },
  {
    className: "DefinedNames",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "definedNames",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "definedName", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "DifferentialFormats",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "dxfs",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "dxf", min: 0, max: "unbounded" }
      ] }
    },
  },
  {
    className: "DifferentialType",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "dxf",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "font", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "numFmt", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "fill", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "alignment", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "border", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "protection", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ExtensionList",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "extLst",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "group", min: 0, max: 1, items: [
          { kind: "sequence", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "ext", min: 0, max: "unbounded" }
          ] }
        ] }
      ] }
    },
  },
  {
    className: "FormControlProperties",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "formControlPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "itemLst", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "IconFilter",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "iconFilter",
    requiredAttrs: [":iconSet", ":iconId"],
  },
  {
    className: "IconSet",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "iconSet",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "cfvo", min: 2, max: "unbounded" },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "cfIcon", min: 0, max: 5 }
      ] }
    },
  },
  {
    className: "IgnoredError",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "ignoredError",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sqref", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "IgnoredErrors",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "ignoredErrors",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "ignoredError", min: 0, max: "unbounded" },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ListItem",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "item",
    requiredAttrs: [":val"],
  },
  {
    className: "ListItems",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "itemLst",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "item", min: 0, max: "unbounded" },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "OlapSlicerCache",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "olap",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "levels", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "selections", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":pivotCacheId"],
  },
  {
    className: "OlapSlicerCacheItem",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "i",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "p", min: 0, max: "unbounded" }
      ] }
    },
    requiredAttrs: [":n"],
  },
  {
    className: "OlapSlicerCacheItemParent",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "p",
    requiredAttrs: [":n"],
  },
  {
    className: "OlapSlicerCacheLevelData",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "level",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "ranges", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":uniqueName", ":count"],
  },
  {
    className: "OlapSlicerCacheLevelsData",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "levels",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "level", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "OlapSlicerCacheRange",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "range",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "i", min: 1, max: "unbounded" }
      ] }
    },
    requiredAttrs: [":startItem"],
  },
  {
    className: "OlapSlicerCacheRanges",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "ranges",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "range", min: 0, max: "unbounded" }
      ] }
    },
  },
  {
    className: "OlapSlicerCacheSelection",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "selection",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "p", min: 0, max: "unbounded" }
      ] }
    },
    requiredAttrs: [":n"],
  },
  {
    className: "OlapSlicerCacheSelections",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "selections",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "selection", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "OleItem",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "oleItem",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "values", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":name"],
  },
  {
    className: "PivotArea",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotArea",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "references", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "PivotAreas",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotAreas",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotArea", min: 0, max: "unbounded" }
      ] }
    },
  },
  {
    className: "PivotCaches",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotCaches",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotCache", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "PivotChange",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotChange",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "editValue", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "tupleItems", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "PivotChanges",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotChanges",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotChange", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "PivotEdit",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotEdit",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "userEdit", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "tupleItems", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotArea", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "PivotEdits",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotEdits",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotEdit", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "PivotEditValue",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "editValue",
    requiredAttrs: [":valueType"],
  },
  {
    className: "PivotTableDefinition",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotTableDefinition",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotEdits", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotChanges", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "conditionalFormats", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "PivotUserEdit",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "userEdit",
    particle: {
      root: { kind: "choice", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "editValue", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "ProtectedRange",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "protectedRange",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sqref", min: 1, max: 1 }
      ] }
    },
    requiredAttrs: [":name"],
    attrConstraints: [
      { qname: ":password", minLength: 2, maxLength: 2 },
    ],
  },
  {
    className: "ProtectedRanges",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "protectedRanges",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "protectedRange", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SetLevel",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "setLevel",
    requiredAttrs: [":hierarchy"],
  },
  {
    className: "SetLevels",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "setLevels",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "setLevel", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "Slicer",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicer",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":name", ":cache", ":rowHeight"],
  },
  {
    className: "SlicerCache",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerCache",
    requiredAttrs: ["r:id"],
  },
  {
    className: "SlicerCacheData",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "data",
    particle: {
      root: { kind: "choice", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "olap", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "tabular", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "SlicerCacheDefinition",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerCacheDefinition",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotTables", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "data", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":name", ":sourceName"],
  },
  {
    className: "SlicerCacheDefinitionExtensionList",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "extLst",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "ext", min: 0, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SlicerCachePivotTable",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotTable",
    requiredAttrs: [":tabId", ":name"],
  },
  {
    className: "SlicerCachePivotTables",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "pivotTables",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "pivotTable", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SlicerCaches",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerCaches",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "slicerCache", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SlicerList",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerList",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "slicer", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SlicerRef",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicer",
    requiredAttrs: ["r:id"],
  },
  {
    className: "Slicers",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicers",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "slicer", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SlicerStyle",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerStyle",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "slicerStyleElements", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":name"],
  },
  {
    className: "SlicerStyleElement",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerStyleElement",
    requiredAttrs: [":type"],
  },
  {
    className: "SlicerStyleElements",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerStyleElements",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "slicerStyleElement", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "SlicerStyles",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "slicerStyles",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "slicerStyle", min: 0, max: "unbounded" }
      ] }
    },
    requiredAttrs: [":defaultSlicerStyle"],
  },
  {
    className: "SortCondition",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "sortCondition",
    requiredAttrs: [":ref"],
  },
  {
    className: "SourceConnection",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "sourceConnection",
    requiredAttrs: [":name"],
  },
  {
    className: "Sparkline",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "sparkline",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sqref", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "SparklineGroup",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "sparklineGroup",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorSeries", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorNegative", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorAxis", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorMarkers", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorFirst", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorLast", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorHigh", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "colorLow", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "f", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sparklines", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "SparklineGroups",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "sparklineGroups",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sparklineGroup", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "Sparklines",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "sparklines",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "sparkline", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "TabularSlicerCache",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "tabular",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "items", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":pivotCacheId"],
  },
  {
    className: "TabularSlicerCacheItem",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "i",
    requiredAttrs: [":x"],
  },
  {
    className: "TabularSlicerCacheItems",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "items",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "i", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "TupleItems",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "tupleItems",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "tupleItem", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "TupleSet",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "tupleSet",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "headers", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "rows", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "TupleSetHeaders",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "headers",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "header", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "TupleSetRow",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "row",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "rowItem", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "TupleSetRows",
    namespaceUri: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    localName: "rows",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main", local: "row", min: 1, max: "unbounded" }
      ] }
    },
  },
];
