// THIS FILE IS GENERATED BY tools/schema-codegen/gen-constraints.ts. DO NOT EDIT.
// Source: ../../github/Open-XML-SDK/data/schemas/schemas_openxmlformats_org_drawingml_2006_spreadsheetDrawing.json
import type { ElementConstraint } from "../types.js";

export const constraints: ReadonlyArray<ElementConstraint> = [
  {
    className: "AbsoluteAnchor",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "absoluteAnchor",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "pos", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "ext", min: 1, max: 1 },
        { kind: "group", min: 1, max: 1, items: [
          { kind: "sequence", min: 1, max: 1, items: [
            { kind: "choice", min: 1, max: 1, items: [
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "sp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "grpSp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "graphicFrame", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cxnSp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "pic", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "contentPart", min: 1, max: 1, initialVersion: "Office2010" }
            ] }
          ] }
        ] },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "clientData", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "BlipFill",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "blipFill",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "blip", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "srcRect", min: 0, max: 1 },
        { kind: "group", min: 0, max: 1, items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "tile", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "stretch", min: 1, max: 1 }
          ] }
        ] }
      ] }
    },
  },
  {
    className: "ConnectionShape",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cxnSp",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvCxnSpPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "spPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "style", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ContentPart",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "contentPart",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvContentPartPr", min: 0, max: 1, initialVersion: "Office2010" },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvPr", min: 0, max: 1, initialVersion: "Office2010" },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "xfrm", min: 0, max: 1, initialVersion: "Office2010" },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "extLst", min: 0, max: 1, initialVersion: "Office2010" }
      ] }
    },
    requiredAttrs: ["r:id"],
  },
  {
    className: "Extent",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "ext",
    requiredAttrs: [":cx", ":cy"],
    attrConstraints: [
      { qname: ":cx", minValue: 0, maxValue: 2147483647 },
      { qname: ":cy", minValue: 0, maxValue: 2147483647 },
    ],
  },
  {
    className: "FromMarker",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "from",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "col", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "colOff", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "row", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "rowOff", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "GraphicFrame",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "graphicFrame",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvGraphicFramePr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "xfrm", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "graphic", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "GroupShape",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "grpSp",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvGrpSpPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "grpSpPr", min: 1, max: 1 },
        { kind: "choice", min: 0, max: "unbounded", items: [
          { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "sp", min: 1, max: 1 },
          { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "grpSp", min: 1, max: 1 },
          { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "graphicFrame", min: 1, max: 1 },
          { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cxnSp", min: 1, max: 1 },
          { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "pic", min: 1, max: 1 },
          { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "contentPart", min: 1, max: 1, initialVersion: "Office2010" }
        ] }
      ] }
    },
  },
  {
    className: "GroupShapeProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "grpSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "xfrm", min: 0, max: 1 },
        { kind: "group", min: 0, max: 1, items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "noFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "solidFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "gradFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "blipFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "pattFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "grpFill", min: 1, max: 1 }
          ] }
        ] },
        { kind: "group", min: 0, max: 1, items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "effectLst", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "effectDag", min: 1, max: 1 }
          ] }
        ] },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "scene3d", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualConnectionShapeProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "nvCxnSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvCxnSpPr", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualConnectorShapeDrawingProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cNvCxnSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "cxnSpLocks", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "stCxn", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "endCxn", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualDrawingProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cNvPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "hlinkClick", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "hlinkHover", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
    requiredAttrs: [":id", ":name"],
  },
  {
    className: "NonVisualGraphicFrameDrawingProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cNvGraphicFramePr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "graphicFrameLocks", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualGraphicFrameProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "nvGraphicFramePr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvGraphicFramePr", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualGroupShapeDrawingProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cNvGrpSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "grpSpLocks", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualGroupShapeProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "nvGrpSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvGrpSpPr", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualPictureDrawingProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cNvPicPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "picLocks", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualPictureProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "nvPicPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvPicPr", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualShapeDrawingProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "cNvSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "spLocks", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "NonVisualShapeProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "nvSpPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cNvSpPr", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "OneCellAnchor",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "oneCellAnchor",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "from", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "ext", min: 1, max: 1 },
        { kind: "group", min: 1, max: 1, items: [
          { kind: "sequence", min: 1, max: 1, items: [
            { kind: "choice", min: 1, max: 1, items: [
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "sp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "grpSp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "graphicFrame", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cxnSp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "pic", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "contentPart", min: 1, max: 1, initialVersion: "Office2010" }
            ] }
          ] }
        ] },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "clientData", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "Picture",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "pic",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvPicPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "blipFill", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "spPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "style", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "Position",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "pos",
    requiredAttrs: [":x", ":y"],
    attrConstraints: [
      { qname: ":x", minValue: -27273042329600, maxValue: 27273042316900 },
      { qname: ":y", minValue: -27273042329600, maxValue: 27273042316900 },
    ],
  },
  {
    className: "Shape",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "sp",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "nvSpPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "spPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "style", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "txBody", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ShapeProperties",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "spPr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "xfrm", min: 0, max: 1 },
        { kind: "group", min: 0, max: 1, items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "custGeom", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "prstGeom", min: 1, max: 1 }
          ] }
        ] },
        { kind: "group", min: 0, max: 1, items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "noFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "solidFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "gradFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "blipFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "pattFill", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "grpFill", min: 1, max: 1 }
          ] }
        ] },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "ln", min: 0, max: 1 },
        { kind: "group", min: 0, max: 1, items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "effectLst", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "effectDag", min: 1, max: 1 }
          ] }
        ] },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "scene3d", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "sp3d", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "extLst", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "ShapeStyle",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "style",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "lnRef", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "fillRef", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "effectRef", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "fontRef", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "TextBody",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "txBody",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "bodyPr", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "lstStyle", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "p", min: 1, max: "unbounded" }
      ] }
    },
  },
  {
    className: "ToMarker",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "to",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "col", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "colOff", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "row", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "rowOff", min: 1, max: 1 }
      ] }
    },
  },
  {
    className: "Transform",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "xfrm",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "off", min: 0, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/main", local: "ext", min: 0, max: 1 }
      ] }
    },
  },
  {
    className: "TwoCellAnchor",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "twoCellAnchor",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "from", min: 1, max: 1 },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "to", min: 1, max: 1 },
        { kind: "group", min: 1, max: 1, items: [
          { kind: "sequence", min: 1, max: 1, items: [
            { kind: "choice", min: 1, max: 1, items: [
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "sp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "grpSp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "graphicFrame", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "cxnSp", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "pic", min: 1, max: 1 },
              { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "contentPart", min: 1, max: 1, initialVersion: "Office2010" }
            ] }
          ] }
        ] },
        { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "clientData", min: 1, max: 1 }
      ] }
    },
    attrConstraints: [
      { qname: ":editAs", enumMembers: ["twoCell", "oneCell", "absolute"] },
    ],
  },
  {
    className: "WorksheetDrawing",
    namespaceUri: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    localName: "wsDr",
    particle: {
      root: { kind: "sequence", min: 1, max: 1, items: [
        { kind: "group", min: 0, max: "unbounded", items: [
          { kind: "choice", min: 1, max: 1, items: [
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "twoCellAnchor", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "oneCellAnchor", min: 1, max: 1 },
            { kind: "leaf", ns: "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing", local: "absoluteAnchor", min: 1, max: 1 }
          ] }
        ] }
      ] }
    },
  },
];
